
POST http://127.0.0.1:5000/api/v1/email/email-verification 
Content-Type: application/json;

{
    "data": {"validation-url": "https://google.com"},
    "lang": "password_reset",
    "recipient": "komlankodoh@gmail.com"
}